name: Deploy the project backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  find:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find
        run: pwd
